# https://github.com/craigcitro/r-travis
language: c
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- ./travis-tool.sh bootstrap

env:
global:
- R_BUILD_ARGS="--no-build-vignettes --no-manual"
- R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"

install:
- ./travis-tool.sh install_github rstats-db/RSQLite
- ./travis-tool.sh install_deps
script: ./travis-tool.sh run_tests

notifications:
email:
on_success: change
on_failure: change